<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Liste des projets spécifiques avec des images en ligne
        $projects = [
            [
                'title' => 'École primaire pour enfants défavorisés',
                'short_description' => 'Construction et équipement d\'une école primaire pour offrir une éducation de qualité aux enfants dans les zones rurales.',
                'description' => 'Ce projet vise à construire et équiper une école primaire moderne dans une zone rurale défavorisée. Nous construirons 6 salles de classe, une bibliothèque, une cantine et des installations sanitaires. Ce projet permettra à plus de 300 enfants d\'accéder à une éducation de qualité chaque année.',
                'category' => 'Éducation',
                'type' => 'project',
                'budget' => 45000.00,
                'amount_raised' => 28000.00,
                'status' => 'ongoing',
                'location' => 'Kinshasa',
                'country' => 'Congo',
                'start_date' => now()->subMonths(3),
                'end_date' => now()->addMonths(9),
                'image' => 'https://images.pexels.com/photos/159775/library-la-trobe-study-students-159775.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 300,
                'is_featured' => true,
            ],
            [
                'title' => 'Programme de santé maternelle et infantile',
                'short_description' => 'Amélioration de l\'accès aux soins de santé pour les mères et leurs enfants dans les communautés rurales.',
                'description' => 'Ce programme comprend des consultations prénatales, des vaccinations, des formations en nutrition et l\'équipement de centres de santé. Nous visons à réduire la mortalité maternelle et infantile de 40% dans les zones ciblées.',
                'category' => 'Santé',
                'type' => 'program',
                'budget' => 60000.00,
                'amount_raised' => 45000.00,
                'status' => 'ongoing',
                'location' => 'Kigali',
                'country' => 'Rwanda',
                'start_date' => now()->subMonths(2),
                'end_date' => now()->addMonths(12),
                'image' => 'https://images.pexels.com/photos/3861445/pexels-photo-3861445.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 1500,
                'is_featured' => true,
            ],
            [
                'title' => 'Campagne de reforestation communautaire',
                'short_description' => 'Plantation de 50 000 arbres pour lutter contre la déforestation et le changement climatique.',
                'description' => 'Nous organisons des campagnes de plantation d\'arbres avec les communautés locales. Ce projet inclut la formation des habitants, la fourniture de plants d\'arbres indigènes et le suivi de croissance sur 3 ans. Impact environnemental direct et création d\'emplois locaux.',
                'category' => 'Environnement',
                'type' => 'campaign',
                'budget' => 35000.00,
                'amount_raised' => 35000.00,
                'status' => 'completed',
                'location' => 'Bukavu',
                'country' => 'Congo',
                'start_date' => now()->subMonths(18),
                'end_date' => now()->subMonths(6),
                'image' => 'https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 5000,
                'is_featured' => false,
            ],
            [
                'title' => 'Centre d\'accueil pour enfants de la rue',
                'short_description' => 'Création d\'un centre d\'hébergement et de réinsertion pour les enfants vivant dans la rue.',
                'description' => 'Ce centre offrira un hébergement sécurisé, des repas nutritifs, des soins médicaux, une scolarisation et un accompagnement psychologique. Notre objectif est de réintégrer ces enfants dans leurs familles ou de leur trouver des foyers d\'accueil permanents.',
                'category' => 'Humanitaire',
                'type' => 'project',
                'budget' => 75000.00,
                'amount_raised' => 42000.00,
                'status' => 'ongoing',
                'location' => 'Bujumbura',
                'country' => 'Burundi',
                'start_date' => now()->subMonths(6),
                'end_date' => now()->addMonths(18),
                'image' => 'https://images.pexels.com/photos/2425011/pexels-photo-2425011.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 120,
                'is_featured' => true,
            ],
            [
                'title' => 'Formation professionnelle pour jeunes adultes',
                'short_description' => 'Programme de formation en métiers porteurs pour les jeunes défavorisés âgés de 18 à 30 ans.',
                'description' => 'Nous offrons des formations en électricité, plomberie, couture, agriculture moderne et commerce. Chaque formation dure 6 mois avec stages pratiques inclus. À la fin, nous aidons les participants à trouver un emploi ou à créer leur propre entreprise.',
                'category' => 'Développement',
                'type' => 'program',
                'budget' => 55000.00,
                'amount_raised' => 30000.00,
                'status' => 'ongoing',
                'location' => 'Dakar',
                'country' => 'Sénégal',
                'start_date' => now()->subMonths(1),
                'end_date' => now()->addMonths(11),
                'image' => 'https://images.pexels.com/photos/3184302/pexels-photo-3184302.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 200,
                'is_featured' => false,
            ],
            [
                'title' => 'Approvisionnement en eau potable',
                'short_description' => 'Installation de puits et systèmes de filtration d\'eau dans 5 villages ruraux.',
                'description' => 'Ce projet permettra à plus de 2000 personnes d\'accéder à l\'eau potable. Nous installons des puits équipés de pompes manuelles, des systèmes de filtration et formons les communautés à la maintenance. Impact direct sur la santé et réduction des maladies hydriques.',
                'category' => 'Humanitaire',
                'type' => 'project',
                'budget' => 40000.00,
                'amount_raised' => 25000.00,
                'status' => 'ongoing',
                'location' => 'Bamako',
                'country' => 'Mali',
                'start_date' => now()->subMonths(4),
                'end_date' => now()->addMonths(8),
                'image' => 'https://images.pexels.com/photos/1024311/pexels-photo-1024311.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 2000,
                'is_featured' => false,
            ],
            [
                'title' => 'Soutien aux familles monoparentales',
                'short_description' => 'Programme d\'aide financière et d\'accompagnement pour les mères célibataires en difficulté.',
                'description' => 'Nous offrons une aide mensuelle, des formations en gestion de budget, en recherche d\'emploi et des services de garde d\'enfants. Ce programme permet aux mères de se former ou de travailler tout en s\'assurant que leurs enfants sont bien pris en charge.',
                'category' => 'Soutien aux familles',
                'type' => 'program',
                'budget' => 50000.00,
                'amount_raised' => 38000.00,
                'status' => 'ongoing',
                'location' => 'Bruxelles',
                'country' => 'Belgique',
                'start_date' => now()->subMonths(8),
                'end_date' => now()->addMonths(16),
                'image' => 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 150,
                'is_featured' => true,
            ],
            [
                'title' => 'Lutte contre la malnutrition infantile',
                'short_description' => 'Distribution de compléments nutritionnels et formation des parents sur l\'alimentation équilibrée.',
                'description' => 'Nous distribuons des compléments nutritionnels aux enfants de 6 mois à 5 ans dans les zones à risque. En parallèle, nous organisons des ateliers de nutrition pour les parents et formons des relais communautaires. Suivi médical mensuel inclus.',
                'category' => 'Santé',
                'type' => 'campaign',
                'budget' => 45000.00,
                'amount_raised' => 32000.00,
                'status' => 'ongoing',
                'location' => 'Ouagadougou',
                'country' => 'Burkina Faso',
                'start_date' => now()->subMonths(5),
                'end_date' => now()->addMonths(7),
                'image' => 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 800,
                'is_featured' => false,
            ],
            [
                'title' => 'Bibliothèque mobile pour zones isolées',
                'short_description' => 'Bibliothèque itinérante apportant livres et matériel éducatif aux enfants dans les villages reculés.',
                'description' => 'Un véhicule équipé d\'une bibliothèque visite chaque semaine les villages isolés. Les enfants peuvent emprunter des livres, participer à des animations lecture et avoir accès à des ordinateurs avec connexion internet. Impact : amélioration des résultats scolaires et ouverture culturelle.',
                'category' => 'Éducation',
                'type' => 'program',
                'budget' => 30000.00,
                'amount_raised' => 18000.00,
                'status' => 'ongoing',
                'location' => 'Kigali',
                'country' => 'Rwanda',
                'start_date' => now()->subMonths(2),
                'end_date' => now()->addMonths(10),
                'image' => 'https://images.pexels.com/photos/2566581/pexels-photo-2566581.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 600,
                'is_featured' => false,
            ],
            [
                'title' => 'Réhabilitation de logements insalubres',
                'short_description' => 'Rénovation de 50 logements dans un quartier défavorisé pour améliorer les conditions de vie.',
                'description' => 'Nous rénovons les logements : installation d\'électricité, eau courante, toitures, fenêtres et portes sécurisées. Nous formons également les propriétaires à l\'entretien. Ce projet améliore la sécurité, la santé et la dignité des familles concernées.',
                'category' => 'Humanitaire',
                'type' => 'project',
                'budget' => 80000.00,
                'amount_raised' => 50000.00,
                'status' => 'ongoing',
                'location' => 'Kinshasa',
                'country' => 'Congo',
                'start_date' => now()->subMonths(7),
                'end_date' => now()->addMonths(17),
                'image' => 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 250,
                'is_featured' => true,
            ],
            [
                'title' => 'Centre de prévention du VIH/SIDA',
                'short_description' => 'Centre de dépistage, prévention et accompagnement pour les personnes à risque.',
                'description' => 'Nous offrons des tests gratuits, des préservatifs, des conseils en prévention et un accompagnement psychologique. Organisation de campagnes de sensibilisation dans les écoles et les communautés. Partenariat avec les centres de santé locaux.',
                'category' => 'Santé',
                'type' => 'project',
                'budget' => 65000.00,
                'amount_raised' => 40000.00,
                'status' => 'ongoing',
                'location' => 'Bujumbura',
                'country' => 'Burundi',
                'start_date' => now()->subMonths(3),
                'end_date' => now()->addMonths(15),
                'image' => 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 1000,
                'is_featured' => false,
            ],
            [
                'title' => 'Projet d\'agriculture durable',
                'short_description' => 'Formation en techniques agricoles durables et fourniture de semences et outils aux agriculteurs.',
                'description' => 'Nous formons les agriculteurs aux techniques de permaculture, de rotation des cultures et de gestion de l\'eau. Distribution de semences résistantes et d\'outils agricoles. Création de coopératives pour la commercialisation. Objectif : améliorer les rendements de 30% tout en préservant l\'environnement.',
                'category' => 'Développement',
                'type' => 'program',
                'budget' => 55000.00,
                'amount_raised' => 35000.00,
                'status' => 'ongoing',
                'location' => 'Dakar',
                'country' => 'Sénégal',
                'start_date' => now()->subMonths(4),
                'end_date' => now()->addMonths(12),
                'image' => 'https://images.pexels.com/photos/1309766/pexels-photo-1309766.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 300,
                'is_featured' => false,
            ],
            [
                'title' => 'Aide d\'urgence aux réfugiés',
                'short_description' => 'Distribution de kits d\'urgence (nourriture, eau, couvertures, médicaments) aux réfugiés.',
                'description' => 'En réponse à une crise humanitaire, nous distribuons des kits de survie aux familles déplacées. Chaque kit contient de la nourriture pour 1 mois, des couvertures, des moustiquaires, des médicaments de base et des produits d\'hygiène. Coordination avec les autorités locales et les autres ONG.',
                'category' => 'Urgence',
                'type' => 'campaign',
                'budget' => 70000.00,
                'amount_raised' => 70000.00,
                'status' => 'completed',
                'location' => 'Burkina Faso',
                'country' => 'Burkina Faso',
                'start_date' => now()->subMonths(12),
                'end_date' => now()->subMonths(3),
                'image' => 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 2500,
                'is_featured' => true,
            ],
            [
                'title' => 'Programme de scolarisation des filles',
                'short_description' => 'Bourses d\'études et accompagnement pour permettre aux filles d\'aller à l\'école secondaire.',
                'description' => 'Nous attribuons des bourses d\'études complètes (frais de scolarité, uniformes, fournitures) à 100 filles méritantes. Nous organisons également des ateliers de sensibilisation sur l\'importance de l\'éducation des filles et assurons un suivi académique et psychologique.',
                'category' => 'Éducation',
                'type' => 'program',
                'budget' => 48000.00,
                'amount_raised' => 33000.00,
                'status' => 'ongoing',
                'location' => 'Kinshasa',
                'country' => 'Congo',
                'start_date' => now()->subMonths(6),
                'end_date' => now()->addMonths(18),
                'image' => 'https://images.pexels.com/photos/2081199/pexels-photo-2081199.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 100,
                'is_featured' => false,
            ],
            [
                'title' => 'Protection des droits des enfants',
                'short_description' => 'Sensibilisation et défense des droits des enfants, lutte contre le travail des mineurs.',
                'description' => 'Nous menons des campagnes de sensibilisation sur les droits de l\'enfant, formons les enseignants et les parents, et intervenons dans les cas de violations. Collaboration avec les autorités pour faire appliquer les lois protégeant les enfants. Création d\'un réseau d\'alerte communautaire.',
                'category' => 'Enfants',
                'type' => 'program',
                'budget' => 52000.00,
                'amount_raised' => 29000.00,
                'status' => 'ongoing',
                'location' => 'Kigali',
                'country' => 'Rwanda',
                'start_date' => now()->subMonths(5),
                'end_date' => now()->addMonths(13),
                'image' => 'https://images.pexels.com/photos/1428787/pexels-photo-1428787.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 2000,
                'is_featured' => false,
            ],
            [
                'title' => 'Événement de collecte de fonds annuel',
                'short_description' => 'Grande soirée de gala avec concerts, expositions et vente aux enchères au profit de nos projets.',
                'description' => 'Notre événement annuel réunit bienfaiteurs, artistes et partenaires pour une soirée de solidarité. Au programme : concerts, expositions d\'art, vente aux enchères d\'œuvres et témoignages de bénéficiaires. L\'argent collecté finance plusieurs de nos projets en cours.',
                'category' => 'Développement',
                'type' => 'event',
                'budget' => 35000.00,
                'amount_raised' => 28000.00,
                'status' => 'ongoing',
                'location' => 'Bruxelles',
                'country' => 'Belgique',
                'start_date' => now()->addMonths(2),
                'end_date' => now()->addMonths(2),
                'image' => 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Projet d\'électrification solaire rurale',
                'short_description' => 'Installation de panneaux solaires dans 10 villages pour l\'éclairage et l\'alimentation électrique.',
                'description' => 'Nous installons des systèmes solaires photovoltaïques dans les écoles, centres de santé et maisons communautaires. Formation de techniciens locaux pour la maintenance. Impact : amélioration de l\'éducation (étude le soir), conservation des vaccins, développement économique local.',
                'category' => 'Développement',
                'type' => 'project',
                'budget' => 85000.00,
                'amount_raised' => 52000.00,
                'status' => 'ongoing',
                'location' => 'Bamako',
                'country' => 'Mali',
                'start_date' => now()->subMonths(8),
                'end_date' => now()->addMonths(16),
                'image' => 'https://images.pexels.com/photos/159775/library-la-trobe-study-students-159775.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 5000,
                'is_featured' => true,
            ],
            [
                'title' => 'Programme d\'alphabétisation pour adultes',
                'short_description' => 'Cours d\'alphabétisation gratuits pour les adultes qui n\'ont jamais eu la chance d\'aller à l\'école.',
                'description' => 'Nous organisons des cours d\'alphabétisation adaptés aux adultes dans les langues locales et en français. Les cours ont lieu en soirée pour permettre aux participants de travailler la journée. Objectif : autonomie dans la vie quotidienne et meilleures opportunités professionnelles.',
                'category' => 'Éducation',
                'type' => 'program',
                'budget' => 38000.00,
                'amount_raised' => 22000.00,
                'status' => 'ongoing',
                'location' => 'Ouagadougou',
                'country' => 'Burkina Faso',
                'start_date' => now()->subMonths(3),
                'end_date' => now()->addMonths(9),
                'image' => 'https://images.pexels.com/photos/247431/pexels-photo-247431.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 400,
                'is_featured' => false,
            ],
            [
                'title' => 'Soins vétérinaires pour bétail',
                'short_description' => 'Vaccination et soins vétérinaires gratuits pour le bétail des éleveurs de la région.',
                'description' => 'Nous organisons des campagnes de vaccination et de soins vétérinaires pour le bétail (bovins, caprins, ovins). Formation des éleveurs sur les pratiques d\'élevage saines. Impact : réduction de la mortalité du bétail, amélioration des revenus des familles d\'éleveurs, sécurité alimentaire.',
                'category' => 'Développement',
                'type' => 'campaign',
                'budget' => 42000.00,
                'amount_raised' => 27000.00,
                'status' => 'ongoing',
                'location' => 'Dakar',
                'country' => 'Sénégal',
                'start_date' => now()->subMonths(2),
                'end_date' => now()->addMonths(10),
                'image' => 'https://images.pexels.com/photos/933964/pexels-photo-933964.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 600,
                'is_featured' => false,
            ],
            [
                'title' => 'Réinsertion sociale des ex-détenus',
                'short_description' => 'Accompagnement personnalisé pour aider les ex-détenus à se réinsérer dans la société.',
                'description' => 'Nous offrons un hébergement temporaire, une formation professionnelle, une aide à la recherche d\'emploi et un suivi psychologique. Organisation de groupes de parole et création d\'un réseau d\'employeurs partenaires. Objectif : réduire la récidive et permettre une seconde chance.',
                'category' => 'Développement',
                'type' => 'program',
                'budget' => 58000.00,
                'amount_raised' => 35000.00,
                'status' => 'ongoing',
                'location' => 'Bruxelles',
                'country' => 'Belgique',
                'start_date' => now()->subMonths(6),
                'end_date' => now()->addMonths(12),
                'image' => 'https://images.pexels.com/photos/1367272/pexels-photo-1367272.jpeg?auto=compress&cs=tinysrgb&w=800',
                'beneficiaries_count' => 80,
                'is_featured' => false,
            ],
        ];

        // Créer les 20 projets
        foreach ($projects as $index => $projectData) {
            Activity::create(array_merge($projectData, [
                'tags' => ['humanitaire', 'solidarité', 'développement'],
                'impact' => 'Ce projet aura un impact durable sur la vie de ' . number_format($projectData['beneficiaries_count'], 0, ',', ' ') . ' personnes, améliorant leur qualité de vie et leurs perspectives d\'avenir.',
                'results' => 'Résultats attendus : amélioration significative des conditions de vie, développement des compétences et autonomisation des bénéficiaires.',
                'impact_metrics' => [
                    'beneficiaries_direct' => $projectData['beneficiaries_count'],
                    'beneficiaries_indirect' => $projectData['beneficiaries_count'] * 3,
                    'sustainability_score' => rand(7, 10),
                ],
                'images' => [
                    $projectData['image'],
                    'https://images.pexels.com/photos/3184460/pexels-photo-3184460.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'views_count' => rand(50, 3000),
                'likes_count' => rand(10, 300),
            ]));
        }

        $this->command->info('20 projets créés avec succès !');
    }
}
